### ISSUE TITLE
Change how status is displayed for submissions in the Submissions table

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#568] opened 2018-06-14 19:24 UTC
Status column should be changed to be calculated based on the combined statuses of all `repositoryCopy`s associated with the submission

* No `repositoryCopy` objects associated with the submission: display nothing
* `submission.source="other" && submission.submitted=false`: display `Manuscript expected`
* All `repositoryCopy` objects have `copyStatus=complete`: display status `complete`
* Other combination of `repositoryCopy.copyStatus`: display a link saying "See details" that links to the submission details page. This part relates to #539 which will have a nicer way of displaying all `repositoryCopy.copyStatus`

-----

**Updated specs: https://github.com/OA-PASS/pass-ember/issues/568#issuecomment-397420573**

**Comment by karenhanson** [comment] 2018-06-14 19:30
@jabrah I believe status display is still undecided unless you recently talked to @htpvu. The problem is that we may not have a RepositoryCopy for every Deposit. Some Deposits may be accepted by the target Repository and that's the last we know of them.

**Comment by emetsger** [comment] 2018-06-14 19:42
@jabrah @karenhanson @htpvu yes this probably deserves larger discussion.

## Concrete example: NIH submissions 

1. Deposit Services processes the `Submission`
2. Upon successful processing this results in a `Deposit` with a status of `SUBMITTED`. 
    * A `tar.gz` is dropped off at the NIH FTP server.
    * All we know at that time is whether or not the bytes of the package were transferred successfully
    * There is no indication of acceptance of custody from NIH at the time the package is created and dropped off on the FTP server.
    * In the absence of an acceptance of custody, we ought to leave the status of the `Deposit` as `SUBMITTED`.
3. No `RepositoryCopy` is created.
    * Because there is no acceptance of custody, there's no location for a `RepositoryCopy` to reference, so at the moment Deposit Services does not create one.

After some time in the future, the NIH will process the `.tar.gz` file we dropped off, and they send an email that indicates the acceptance (or not) of custody.

After that email is received, we can change the status of the `Deposit` to `ACCEPTED` (or `REJECTED`, if they do not take custody).  If the email indicates a location of the content, we can create a `RepositoryCopy`.

**Comment by htpvu** [comment] 2018-06-14 20:00
FOR SUBMISSION TABLE: 

Status column should be changed to be calculated based on the combined statuses of all `repositoryCopys` associated with the submission
* `submission.source="pass"` && `submission.submitted=true` && no `repoCopy`: display `submitted`
* `submission.source="other"` && `submission.submitted=false` && no `repoCopy` : display Manuscript expected
* `repoCopy.copyStatus="complete"`: display `complete`
* Other combination of repositoryCopy.copyStatus: display a link saying "See details" that links to the submission details page. This part relates to #539 which will have a nicer way of displaying all repositoryCopy.copyStatus

**Comment by htpvu** [comment] 2018-06-14 20:01
The nuances of individual deposits and repocopies as they are related to a single submission should be captured in the submission details page

**Comment by jabrah** [comment] 2018-06-17 03:14
Table incorrectly showing `Submitted` instead of `See details` when a `repositoryCopy.copyStatus=stalled`

**Comment by htpvu** [comment] 2018-06-19 02:55
looks good.

**Closed by htpvu** 2018-06-19 02:55 UTC
Labels: Submissions table, blocker
