### ISSUE TITLE
Most columns in Submissions table cannot be sorted

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#251] opened 2018-05-04 23:39 UTC
This seems to be a quirk of the `ember-models-table` that we are using. The default sorting behavior checks either `propertyName` or `sortBy` property on the column. Having a custom table cell displaying data from referenced objects, especially a collection of referenced objects like `submission.repositories` seem to trip up the sorting behavior.

Next step: try investigating declaring a custom sort function per column? https://github.com/onechiporenko/ember-models-table/pull/308

**Comment by htpvu** [comment] 2018-05-05 12:18
This is duplicate of 181

**Closed** 2018-05-07 12:58 UTC
