### ISSUE TITLE
All submissions seem fail when clicking submit against pass-docker due to incorrect context

### ISSUE THREAD

**Issue by birkland** [OA-PASS/pass-ember#767] opened 2018-11-03 00:37 UTC
Using the model-3.0 branch of pass-docker, building the `ember` image by setting `EMBER_GIT_BRANCH=f7abcc6f58816469367528c33947923f6689f8d4` and `docker-compose build ember` (after un-pinning ember from a hash in `docker-compose.yml`, of source), I have been unable to get any submissions to succeed.  They all fail when clicking the final submit button.

What happens upon clicking `submit` is:
* A red box (error dialog?) appears in the upper right corner, but it has no text in it
* The spinner in the middle of the screen spins infinitely

Looking at the browser console, there is a message `Failed to load resource: the server responded with a status of 400 (400)`

Looking at Fedora logs reveals an exception:
`00:00:45.890 [           ajp-nio-8009-exec-4] WARN (DeserializationFilter) Bad request
org.dataconservancy.fcrepo.jsonld.BadRequestException: Unknown attribute submissionStatus
        at org.dataconservancy.fcrepo.jsonld.JsonldNtriplesTranslator.verify(JsonldNtriplesTranslator.java:121)
`

Setting logging to DEBUG reveals a bad submission from Ember.  The data model is consistent with 3.2, but the declared context is 2.3.  There are no environment variables specifying a context of any kind in the `.env`, so it must be baked into Ember somehow?
```
{  
   "@context":"https://oa-pass.github.io/pass-data-model/src/main/resources/context-2.2.jsonld",
   "@id":"",
   "@type":"Submission",
   "aggregatedDepositStatus":"not-started",
   "submittedDate":"2018-11-03T00:00:45.410Z",
   "source":"pass",
   "metadata":"[{\"id\":\"JScholarship\",\"data\":{\"authors\":[{\"author\":\"Tania Marchbank\"},{\"author\":\"Nikki Mandir\"},{\"author\":\"Denis Calnan\"},{\"author\":\"Robert A. Goodlad\"},{\"author\":\"Theo Podas\"},{\"author\":\"Raymond J. Playford\"}],\"embargo\":\"NON-EXCLUSIVE LICENSE FOR USE OF MATERIALS This non-exclusive license defines the terms for the deposit of Materials in all formats into the digital repository of materials collected, preserved and made available through the Johns Hopkins Digital Repository, JScholarship. The Contributor hereby grants to Johns Hopkins a royalty free, non-exclusive worldwide license to use, re-use, display, distribute, transmit, publish, re-publish or copy the Materials, either digitally or in print, or in any other medium, now or hereafter known, for the purpose of including the Materials hereby licensed in the collection of materials in the Johns Hopkins Digital Repository for educational use worldwide. In some cases, access to content may be restricted according to provisions established in negotiation with the copyright holder. This license shall not authorize thecommercial use of the Materials by Johns Hopkins or any other person or organization, but such Materials shall be restricted to non-profit educational use. Persons may apply for commercial use by contacting the copyright holder. Copyright and any other intellectual property right in or to the Materials shall not be transferred by this agreement and shall remain with the Contributor, or the Copyright holder if different from the Contributor. Other than this limited license, the Contributor or Copyright holder retains all rights, title, copyright and other interest in the images licensed. If the submission contains material for which the Contributor does not hold copyright, the Contributor represents that s/he has obtained the permission of the Copyright owner to grant Johns Hopkins the rights required by this license, and that such third-party owned material is clearly identified and acknowledged within the text or content of the submission. If the submission is based upon work that has been sponsored or supported by an agency or organization other than Johns Hopkins,the Contributor represents that s/he has fulfilled any right of review or other obligations required by such contract or agreement. Johns Hopkins will not make any alteration, other than as allowed by this license, to your submission. This agreement embodies the entire agreement of the parties. No modification of this agreement shall be of any effect unless it is made in writing and signed by all of the parties to the agreement.\",\"agreement-to-deposit\":\"true\"}},{\"id\":\"common\",\"data\":{\"title\":\"Specific protein supplementation using soya, casein or whey differentially affects regional gut growth and luminal growth factor bioactivity in rats; implications for the treatment of gut injury and stimulating repair\",\"journal-title\":\"Food & Function\",\"volume\":\"9\",\"issue\":\"1\",\"ISSN\":\"2042-6496,2042-650X\",\"publisher\":\"Royal Society of Chemistry (RSC)\",\"abstract\":\"Differential enhancement of luminal growth factor bioactivity and targeted regional gut growth occurs dependent on dietary protein supplement.\",\"authors\":[{\"author\":\"Tania Marchbank\"},{\"author\":\"Nikki Mandir\"},{\"author\":\"Denis Calnan\"},{\"author\":\"Robert A. Goodlad\"},{\"author\":\"Theo Podas\"},{\"author\":\"Raymond J. Playford\"}]}},{\"id\":\"crossref\",\"data\":{\"doi\":\"10.1039/c7fo01251a\",\"publisher\":\"Royal Society of Chemistry (RSC)\",\"journal-title-short\":\"Food Funct.\"}},{\"id\":\"pmc\",\"data\":{\"nlmta\":\"Food Funct\"}},{\"id\":\"agent_information\",\"data\":{\"information\":{\"name\":\"Chrome\",\"version\":\"71\"}}}]",
   "submitted":false,
   "submissionStatus":null,
   "submitterName":null,
   "submitterEmail":null,
   "submitter":"https://pass.local/fcrepo/rest/users/0f/46/19/45/0f461945-d381-460e-9cc1-be4b246faa95",
   "preparers":null,
   "publication":"https://pass.local/fcrepo/rest/publications/96/aa/cb/fd/96aacbfd-96d0-432d-80be-9c1d2e6cf034",
   "repositories":[  
      "https://pass.local/fcrepo/rest/repositories/41/96/0a/92/41960a92-d3f8-4616-86a6-9e9cadc1a269",
      "https://pass.local/fcrepo/rest/repositories/77/64/12/ec/776412ec-0f5e-488e-97dc-15bb427d27e2"
   ],
   "grants":[  
      "https://pass.local/fcrepo/rest/grants/3c/2d/2b/e9/3c2d2be9-e950-4b74-9699-246ebb31fcc9"
   ]
}
```

**Comment by karenhanson** [comment] 2018-11-03 04:55
I think this may be from `pass-docker/ember/Dockerfile`
https://github.com/OA-PASS/pass-docker/issues/133

**Comment by birkland** [comment] 2018-11-04 16:18
Interesting.  Is there any way Ember can use the one it's model is coded for by default?  The analogy is the Java client.  It is unnecessary to set an evironment variable for that, because the correct one is baked in; any value other than the baked in one is incorrect.   The same "there is only one correct context" principle is true for ember, so it would seem to reduce risk if the context were internal.

**Comment by karenhanson** [comment] 2018-11-06 16:50
@birkland I think we can close this - but need to add an error handling issue right?

**Comment by karenhanson** [comment] 2018-11-09 23:10
Closing this it was caused by an bad context reference in Dockerfile. The reference has been removed. Will open a new issue for the error handling

**Closed by karenhanson** 2018-11-09 23:10 UTC
